language: java
jdk: oraclejdk8
services: mysql
before_install:
  - mysql -uroot -e 'DROP DATABASE IF EXISTS auth_db'
  - mysql -uroot -e 'CREATE DATABASE IF NOT EXISTS auth_db;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
script: mvn clean install sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=5e1d0fe1fe34394952a7eed5a6ec2b9e7074e338
after_success:
  - mvn clean cobertura:cobertura coveralls:report
